### ISSUE TITLE
Фидбек на домашку №2

### ISSUE THREAD

**Issue by tiny-kottan** [MarinaZadoyanchuk/kottans-js-2016#5]
Kudos for 2 `.match`
1. `!~jsClassIndexes.indexOf(classPosition)` -> `!jsClassIndexes.includes(classPosition)`
2. `jsClass.match(jsReg)[2]` -> could have used [non-capturing group](http://www.regular-expressions.info/brackets.html#noncap) and just take `1` (so you don't have to rework your code any time you add group, you just add it to regexp)
3. Personal preference – use const instead of let where applicable. 

``````
let filteredClasses = classes.filter((item) => {
    return !bootstrapReg.test(item);
  });
``` -> could have been `…classes.filter(item => !bootstrapReg.test(item));`
``````

**Comment by sudodoki** [comment]
👍
